---

kind: pipeline
type: kubernetes
name: lint

steps:
  - name: hadolint
    image: hadolint/hadolint:v2.12.0-alpine
    commands:
      - hadolint --failure-threshold warning Dockerfile

---

kind: pipeline
type: kubernetes
name: release

steps:
  - name: generate-changelog
    image: naorlivne/drone-github-changelog-generator
    environment:
      CHANGELOG_GITHUB_TOKEN:
        from_secret: github_token
    settings:
      github_user: agrrh
      github_project: tg-sender
      output_path: CHANGELOG.md

  - name: changelog
    image: appleboy/drone-git-push
    settings:
      branch: master
      remote: git@github.com:agrrh/tg-sender.git
      # remote_name: origin
      commit: true
      commit_message: "[skip ci] changelog bump"
      author_name: drone-gh
      author_email: drone-gh@agrrh.com
      ssh_key:
        from_secret: github_ssh_key

trigger:
  event:
    - push
    - tag
  ref:
    - refs/heads/master
    - refs/tags/**

---

kind: pipeline
type: kubernetes
name: publish

depends_on:
  - lint
  - release

steps:
  - name: docker-hub
    image: plugins/docker
    settings:
      username: agrrh
      password:
        from_secret: docker_password
      repo: agrrh/tg-sender
      auto_tag: true

trigger:
  event:
    - push
    - tag
  ref:
    - refs/heads/master
    - refs/tags/**
